module.exports = {
  title: 'Date',
  default: 'date',
  collated: true,
  status: 'ready',
  preview: '@preview__container',
  variants: [
    {
      name: 'date',
      label: 'Date',
      context: {
        id: 'date-en-gb',
        legend: 'Please enter a date',
        description: 'For example, 31 3 1980',
        dayLabel: 'Day',
        monthLabel: 'Month',
        yearLabel: 'Year',
      },
    },
    {
      name: 'date-cy',
      label: 'Date (Welsh)',
      context: {
        id: 'date-cy',
        legend: 'Rhowch ddyddiad',
        description: 'Er enghraifft, 31 3 1980',
        dayLabel: 'Dydd',
        monthLabel: 'Mis',
        yearLabel: 'Blwyddyn',
      },
    },
    {
      name: 'date-gd',
      label: 'Date (Scottish)',
      context: {
        id: 'date-dg',
        legend: 'Cuir a-steach ceann-là',
        description: 'Mar eisimpleir, 31 3 1980',
        dayLabel: 'Latha',
        monthLabel: 'Mìos',
        yearLabel: 'Bliadhna',
      },
    },
    {
      name: 'date-ga',
      label: 'Date (Irish)',
      context: {
        id: 'date-ga',
        legend: 'Iontráil dáta',
        description: 'Mar shampla, 31 3 1980',
        dayLabel: 'Lá',
        monthLabel: 'Mí',
        yearLabel: 'Bliain',
      },
    },
    {
      name: 'date-pl',
      label: 'Date (Polish)',
      context: {
        id: 'date-pl',
        legend: 'Proszę podać datę',
        description: 'Na przykład, 31 3 1980',
        dayLabel: 'Dzień',
        monthLabel: 'Miesiąc',
        yearLabel: 'Rok',
      },
    },
    {
      name: 'date-of-birth',
      label: 'Date of birth',
      context: {
        id: 'date-of birth',
        legend: 'Please enter your date of birth',
        description: 'For example, 31 3 1980',
        dayLabel: 'Day',
        dayName: 'dob-day',
        monthLabel: 'Month',
        monthName: 'dob-month',
        yearLabel: 'Year',
        yearName: 'dob-year',
      },
    },
    {
      name: 'range',
      label: 'Date Range',
      context: {
        id: 'date-range',
        dayLabel: 'Day',
        monthLabel: 'Month',
        yearLabel: 'Year',
        periodFrom: 'Period from',
        periodTo: 'Period to',
      },
    },
  ],
}
