module.exports = {
  "title": "Select",
  "default": "select",
  "collated": true,
  "status": "ready",
  "variants": [{
    "name": "select",
    "status": "ready",
    "context": {
      "label": "Select",
      "label_text": "Select your favourite cartoon character",
      "label_for": "select",
      "label_description": "As the initial option is selected and disabled this is a mandatory field (once a selection has been made it is not possible to select no option.)",
      "options": [
        {"option_text":"Select an option", "option_value":"", "selected":"selected", "disabled":"disabled"},
        {"option_text":"Bart Simpson", "option_value":"bart"},
        {"option_text":"Homer Simpson", "option_value":"homer"},
        {"option_text":"Marge Simpson", "option_value":"marge"},
        {"option_text":"Lisa Simpson", "option_value":"lisa"},
        {"option_text":"Ned Flanders", "option_value":"ned"},
        {"option_text":"Bugs Bunny", "option_value":"bugs"},
        {"option_text":"The 7 Dwarves: Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey, Doc"},
        {"option_text":"Charlie Brown", "option_value":"charlie brown"},
        {"option_text":"Snoopy", "option_value":"snoopy"},
      ],
    },
  },{
    "name": "select-optional",
    "label": "Select (optional)",
    "status": "ready",
    "context": {
      "label": "Select (optional)",
      "label_text": "Select your favourite cartoon character",
      "label_for": "select-opt",
      "label_description": "As the initial option is selected but not disabled this is an optional field (once a selection has been made it is possible to select no option.)",
      "options": [
        {"option_text":"Select an option", "option_value":"", "selected":"selected", "disabled":""},
        {"option_text":"Bart Simpson", "option_value":"bart"},
        {"option_text":"Homer Simpson", "option_value":"homer"},
        {"option_text":"Marge Simpson", "option_value":"marge"},
        {"option_text":"Lisa Simpson", "option_value":"lisa"},
        {"option_text":"Ned Flanders", "option_value":"ned"},
        {"option_text":"Bugs Bunny", "option_value":"bugs"},
        {"option_text":"The 7 Dwarves: Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey, Doc"},
        {"option_text":"Charlie Brown", "option_value":"charlie brown"},
        {"option_text":"Snoopy", "option_value":"snoopy"},
      ],
    },
  }, {
    "name": "wide",
    "label": "Select (wide)",
    "status": "wip",
    "notes": "Select wide uses the `input--block` class to produce a 100% width variant.",
    "context": {
      "label": "Select (wide)",
      "label_text": "Select your favourite cartoon character",
      "label_for": "select-wide",
      "label_description": "",
      "select_classes": " input--block",
      "options": [
        {"option_text":"Select an option", "option_value":"", "selected":"selected", "disabled":"disabled"},
        {"option_text":"Bart Simpson", "option_value":"bart"},
        {"option_text":"Homer Simpson", "option_value":"homer"},
        {"option_text":"Marge Simpson", "option_value":"marge"},
        {"option_text":"Lisa Simpson", "option_value":"lisa"},
        {"option_text":"Ned Flanders", "option_value":"ned"},
        {"option_text":"Bugs Bunny", "option_value":"bugs"},
        {"option_text":"The 7 Dwarves: Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey & Doc", "option_value": "7 Dwarves"},
        {"option_text":"Charlie Brown", "option_value":"charlie brown"},
        {"option_text":"Snoopy", "option_value":"snoopy"},
      ],
    },
  }, {
    "name": "wide-optional",
    "label": "Select (wide, optional)",
    "status": "wip",
    "notes": "Select wide uses the `input--block` class to produce a 100% width variant.",
    "context": {
      "label": "Select (wide)",
      "label_text": "Select your favourite cartoon character",
      "label_for": "select-wide-optional",
      "label_description": "As the initial option is selected but not disabled this is an optional field (once a selection has been made it is possible to select no option.)",
      "select_classes": " input--block",
      "options": [
        {"option_text":"Select an option", "option_value":"", "selected":"selected", "disabled":""},
        {"option_text":"Bart Simpson", "option_value":"bart"},
        {"option_text":"Homer Simpson", "option_value":"homer"},
        {"option_text":"Marge Simpson", "option_value":"marge"},
        {"option_text":"Lisa Simpson", "option_value":"lisa"},
        {"option_text":"Ned Flanders", "option_value":"ned"},
        {"option_text":"Bugs Bunny", "option_value":"bugs"},
        {"option_text":"The 7 Dwarves: Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey & Doc", "option_value": "7 Dwarves"},
        {"option_text":"Charlie Brown", "option_value":"charlie brown"},
        {"option_text":"Snoopy", "option_value":"snoopy"},
      ],
    },
  }]
}
